// Top ~800 common English words used for test generation.
export const COMMON_WORDS: string[] = [
  "the", "be", "of", "and", "a", "to", "in", "he", "have", "it", "that", "for", "they", "i", "with",
  "as", "not", "on", "she", "at", "by", "this", "we", "you", "do", "but", "from", "or", "which", "one",
  "would", "all", "will", "there", "say", "who", "make", "when", "can", "more", "if", "no", "man",
  "out", "other", "so", "what", "time", "up", "go", "about", "than", "into", "could", "state", "only",
  "new", "year", "some", "take", "come", "these", "know", "see", "use", "get", "like", "then", "first",
  "any", "work", "now", "may", "such", "give", "over", "think", "most", "even", "find", "day", "also",
  "after", "way", "many", "must", "look", "before", "great", "back", "through", "long", "where", "much",
  "should", "well", "people", "down", "own", "just", "because", "good", "each", "those", "feel", "seem",
  "how", "high", "too", "place", "little", "world", "very", "still", "nation", "hand", "old", "life",
  "tell", "write", "become", "here", "show", "house", "both", "between", "need", "mean", "call",
  "develop", "under", "last", "right", "move", "thing", "general", "school", "never", "same", "another",
  "begin", "while", "number", "part", "turn", "real", "leave", "might", "want", "point", "form", "off",
  "child", "few", "small", "since", "against", "ask", "late", "home", "interest", "large", "person",
  "end", "open", "public", "follow", "during", "present", "again", "hold", "govern", "around",
  "possible", "head", "consider", "word", "program", "problem", "however", "lead", "system", "set",
  "order", "eye", "plan", "run", "keep", "face", "fact", "group", "play", "stand", "increase", "early",
  "course", "change", "help", "line", "city", "put", "close", "case", "force", "meet", "once", "water",
  "upon", "war", "build", "hear", "light", "unit", "power", "town", "whole", "air", "side", "kind",
  "next", "live", "together", "love", "always", "story", "study", "food", "sun", "note", "book",
  "music", "field", "morning", "friend", "read", "stop", "without", "idea", "door", "letter", "color",
  "second", "sure", "body", "being", "nothing", "area", "money", "month", "lot", "job", "business",
  "issue", "service", "father", "hour", "game", "member", "law", "car", "community", "name",
  "president", "team", "minute", "kid", "information", "parent", "others", "level", "office",
  "health", "art", "history", "party", "result", "reason", "research", "girl", "guy", "moment",
  "teacher", "education", "foot", "boy", "age", "policy", "process", "market", "sense", "college",
  "death", "experience", "effect", "class", "control", "care", "role", "effort", "rate", "heart",
  "drug", "leader", "voice", "wife", "police", "mind", "price", "report", "decision", "son", "view",
  "relationship", "road", "arm", "difference", "value", "building", "action", "model", "season",
  "society", "tax", "director", "position", "player", "record", "paper", "space", "ground", "event",
  "official", "matter", "center", "couple", "site", "project", "activity", "star", "table", "court",
  "oil", "situation", "cost", "industry", "figure", "street", "image", "phone", "data", "picture",
  "practice", "piece", "land", "product", "doctor", "wall", "patient", "worker", "news", "test",
  "movie", "north", "support", "technology", "step", "baby", "computer", "type", "attention", "film",
  "tree", "source", "truth", "performance", "song", "east", "break", "favorite", "energy", "student",
  "quick", "brown", "fox", "jumps", "lazy", "dog", "rhythm", "strange", "wizard", "puzzle", "jazz",
  "flute", "grape", "ocean", "river", "stone", "cloud", "storm", "breeze", "forest", "meadow",
  "garden", "flower", "silver", "golden", "copper", "crystal", "shadow", "candle", "lantern",
  "bridge", "castle", "knight", "dragon", "phoenix", "falcon", "sparrow", "rabbit", "turtle",
  "dolphin", "whale", "penguin", "panda", "monkey", "tiger", "lion", "zebra", "giraffe", "elephant",
  "coffee", "sugar", "pepper", "bread", "butter", "cheese", "apple", "orange", "banana", "cherry",
  "lemon", "melon", "peach", "berry", "carrot", "onion", "potato", "tomato", "salad", "soup",
  "pasta", "pizza", "delta", "echo", "hotel", "juliet", "kilo", "lima", "mike", "oscar", "papa",
  "romeo", "sierra", "tango", "victor", "whiskey", "alpha", "bravo", "charlie", "quiet", "brave",
  "calm", "eager", "fierce", "gentle", "happy", "jolly", "kindly", "lively", "merry", "noble",
  "polite", "proud", "silly", "smooth", "sturdy", "tender", "vivid", "wise", "zesty", "ample",
  "bright", "crisp", "dense", "eager", "faint", "glad", "humble", "ideal", "jumbo", "keen",
  "lofty", "mellow", "nimble", "optimal", "plush", "quirky", "rapid", "sleek", "swift", "tidy",
  "ultra", "vast", "warm", "young", "zippy", "bold", "cozy", "dizzy", "eloquent", "funky",
];

export const HARD_WORDS: string[] = [
  "algorithm", "architecture", "beautiful", "boundary", "challenge", "character", "complexity",
  "conscious", "curious", "dangerous", "definition", "deliberate", "description", "determined",
  "development", "dictionary", "different", "difficult", "discipline", "discovery", "discussion",
  "efficiency", "electronic", "environment", "equipment", "especially", "experience", "experiment",
  "explanation", "expression", "familiar", "finally", "flourish", "frequency", "friendship",
  "generation", "gratitude", "guarantee", "harmony", "heritage", "hierarchy", "hospital", "hypothesis",
  "imagine", "immediately", "important", "independent", "influence", "information", "initialize",
  "innovation", "institute", "intelligence", "interesting", "investment", "knowledge", "language",
  "library", "machinery", "maintenance", "management", "manufacture", "material", "mathematics",
  "measurement", "mechanism", "medicine", "memory", "mentality", "mineral", "momentum", "monument",
  "mystery", "narrative", "necessary", "nervous", "network", "nobody", "normal", "nutrient",
  "objective", "observation", "obstacle", "opinion", "opportunity", "opposite", "ordinary",
  "organization", "original", "overcome", "parallel", "particular", "passenger", "patience",
  "penalty", "perceive", "performance", "permanent", "personal", "perspective", "phenomenon",
  "philosophy", "physical", "population", "positive", "possibility", "potential", "practical",
  "precious", "presence", "presently", "pressure", "previous", "principle", "priority",
  "probability", "procedure", "professional", "professor", "property", "proportion", "proposal",
  "protection", "psychology", "publish", "purchase", "quality", "quantity", "question", "quotation",
  "realize", "receipt", "recommend", "reduction", "reference", "reflection", "regular", "relevant",
  "reliable", "religion", "remember", "remove", "renewal", "represent", "reputation", "requirement",
  "research", "residence", "resistance", "resource", "responsible", "revenue", "revolution",
  "romantic", "sacrifice", "satisfactory", "scenario", "schedule", "scheme", "scholar", "science",
  "scientific", "sculpture", "secondary", "secretary", "section", "segment", "selection", "sensitive",
  "sentence", "separate", "sequence", "series", "settlement", "significant", "similar", "situated",
  "society", "software", "solution", "somebody", "southern", "statement", "statistics", "structure",
  "strategy", "strength", "stunning", "substance", "substantial", "successful", "sufficient",
  "suggestion", "summary", "suppress", "supreme", "surgery", "surprise", "surround", "survey",
  "survive", "suspect", "sustain", "symbol", "sympathy", "symptom", "talent", "target", "technical",
  "technique", "telephone", "television", "temperature", "temporary", "tendency", "tension",
  "territory", "theory", "therefore", "thorough", "thought", "threat", "tolerate", "tomorrow",
  "tradition", "traffic", "tranquil", "transfer", "transform", "transition", "translate",
  "transport", "treatment", "tremendous", "triumph", "trouble", "university", "unknown", "unusual",
  "valley", "valuable", "variable", "variety", "various", "venture", "version", "vertical", "vessel",
  "veteran", "victory", "violence", "virtue", "visible", "vision", "vocabulary", "volume",
  "volunteer", "wander", "warning", "waterfall", "weather", "wedding", "weekend", "welcome",
  "welfare", "western", "whereas", "willing", "wisdom", "wonderful", "workshop", "worried",
  "worthwhile", "writing", "yesterday",
];

// Short-to-medium famous quotes for quote mode.
export interface Quote {
  text: string;
  author: string;
}

export const QUOTES: Quote[] = [
  { text: "The only way to do great work is to love what you do. If you haven't found it yet, keep looking. Don't settle.", author: "Steve Jobs" },
  { text: "It is not the mountain we conquer, but ourselves. Every limit you break was first drawn in your mind.", author: "Edmund Hillary" },
  { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit that grows quietly day after day.", author: "Will Durant" },
  { text: "Simplicity is the ultimate sophistication. When you strip away everything unnecessary, what remains speaks clearly.", author: "Leonardo da Vinci" },
  { text: "The journey of a thousand miles begins with a single step, and every step after that is easier than the first.", author: "Lao Tzu" },
  { text: "Whether you think you can or you think you can't, you're right. Belief is the engine of every outcome.", author: "Henry Ford" },
  { text: "In the middle of difficulty lies opportunity. The obstacles that slow you down are the ones that teach you the most.", author: "Albert Einstein" },
  { text: "Do not go where the path may lead; go instead where there is no path and leave a trail for others to follow.", author: "Ralph Waldo Emerson" },
  { text: "It always seems impossible until it is done. Then suddenly, the impossible becomes your new starting line.", author: "Nelson Mandela" },
  { text: "Speed is useful only if you are running in the right direction. Practice deliberately, not just diligently.", author: "Joel Barker" },
  { text: "The best time to plant a tree was twenty years ago. The second best time is now, with the hands you have.", author: "Chinese Proverb" },
  { text: "Fall seven times, stand up eight. Persistence is not a talent; it is a choice you make again each morning.", author: "Japanese Proverb" },
  { text: "A ship in harbor is safe, but that is not what ships are built for. Take the risk and sail beyond the lighthouse.", author: "John A. Shedd" },
  { text: "Mistakes are the portals of discovery. Every error you study becomes a lesson; every lesson becomes speed.", author: "James Joyce" },
  { text: "You miss one hundred percent of the shots you do not take. Show up, press the keys, and let practice decide.", author: "Wayne Gretzky" },
  { text: "The mind is not a vessel to be filled but a fire to be kindled. Feed it small challenges every single day.", author: "Plutarch" },
];
