/**
 * Dictionary expansion data — curated bases and morphological families.
 * Consumed by expand-dict.ts which applies orthographic rules and emits
 * src/lib/typing/words-generated.ts.
 *
 * Quality policy: every base below is a common modern English word, and the
 * rule engine only applies standard orthography (drop-e, y->i, explicit CVC
 * doubling sets, explicit irregular maps). Nothing is auto-pluralized unless
 * the regular form is known-safe; irregular/derivative spellings are explicit.
 */

// ---------------------------------------------------------------------------
// Hand-curated new base words, banded by theme (everyday + modern life).
// ---------------------------------------------------------------------------
export const NEW_BASES: string[] = [
  // work & business
  "salary", "career", "employer", "employee", "interview", "resume", "deadline",
  "meeting", "agenda", "manager", "startup", "company", "client", "customer",
  "contract", "invoice", "budget", "profit", "salary", "raise", "promotion",
  "workshop", "training", "skill", "talent", "hire", "retire", "resign",
  "colleague", "committee", "department", "branch", "quarterly", "proposal",
  "strategy", "objective", "target", "deadline", "overtime", "workload",
  "schedule", "calendar", "appointment", "conference", "presentation",
  // tech & digital
  "laptop", "keyboard", "monitor", "printer", "charger", "battery", "cable",
  "wireless", "signal", "password", "username", "website", "browser", "search",
  "download", "upload", "install", "update", "backup", "storage", "memory",
  "screen", "cursor", "folder", "window", "software", "hardware", "network",
  "server", "router", "firewall", "algorithm", "database", "program",
  "digital", "virtual", "online", "offline", "stream", "podcast", "channel",
  "message", "notification", "profile", "hashtag", "emoji", "internet",
  // sports & fitness
  "soccer", "tennis", "hockey", "golf", "boxing", "wrestling", "cycling",
  "swimming", "running", "jogging", "yoga", "stretching", "workout", "gym",
  "coach", "referee", "umpire", "stadium", "arena", "court", "pitch",
  "marathon", "sprint", "relay", " hurdles", "vault", "climbing", "skiing",
  "snowboarding", "surfing", "sailing", "kayak", "bowling", "archery",
  "fencing", "karate", "judo", "taekwondo", "pilates", "treadmill", "dumbbell",
  "whistle", "score", "tiebreaker", "playoff", "championship", "trophy",
  // travel & transport
  "airport", "passport", "luggage", "suitcase", "backpack", "boarding",
  "terminal", "runway", "cockpit", "engine", "bicycle", "scooter", "motorcycle",
  "truck", "van", "taxi", "subway", "tram", "ferry", "cruise", "harbor",
  "journey", "voyage", "itinerary", "souvenir", "landmark", "museum", "gallery",
  "fountain", "plaza", "stadium", "hostel", "resort", "camping", "tent",
  "map", "compass", "binoculars", "camera", "postcard", "guidebook",
  // tools & materials
  "hammer", "screwdriver", "wrench", "pliers", "drill", "ladder", "saw",
  "chisel", "sandpaper", "nail", "screw", "bolt", "hinge", "measuring",
  "welding", "concrete", "timber", "plywood", "plastic", "rubber", "copper",
  "brass", "bronze", "titanium", "marble", "granite", "ceramic", "foam",
  "canvas", "velvet", "nylon", "polyester", "leather", "denim", "linen",
  // feelings & personality
  "courage", "patience", "kindness", "honesty", "loyalty", "humility",
  "gratitude", "empathy", "compassion", "generosity", "confidence", "trust",
  "doubt", "fear", "anger", "joy", "sorrow", "grief", "pride", "shame",
  "envy", "curiosity", "wonder", "boredom", "excitement", "nervousness",
  "calmness", "contentment", "loneliness", "happiness", "sadness", "hope",
  "desire", "passion", "enthusiasm", "optimism", "pessimism", "ambition",
  // body & health
  "elbow", "wrist", "thumb", "ankle", "heel", "spine", "rib", "skull",
  "brain", "lungs", "liver", "kidney", "muscle", "nerve", "artery", "pulse",
  "vision", "hearing", "speech", "breath", "heartbeat", "posture", "balance",
  "hygiene", "vitamin", "protein", "calcium", "fiber", "calorie", "diet",
  "nutrition", "wellness", "therapy", "surgery", "recovery", "symptom",
  "diagnosis", "treatment", "medicine", "dosage", "clinic", "pharmacy",
  // clothing
  "jacket", "sweater", "hoodie", "blouse", "trousers", "jeans", "shorts",
  "skirt", "dress", "gown", "suit", "blazer", "vest", "sock", "shoe", "boot",
  "sandal", "sneaker", "scarf", "glove", "mitten", "belt", "buckle", "button",
  "zipper", "pocket", "sleeve", "collar", "fabric", "pattern", "wardrobe",
  // city & infrastructure
  "avenue", "boulevard", "alley", "sidewalk", "crosswalk", "traffic",
  "intersection", "tunnel", "overpass", "parking", "garage", "basement",
  "attic", "balcony", "chimney", "elevator", "escalator", "staircase",
  "library", "hospital", "pharmacy", "bakery", "butcher", "bookstore",
  "pharmacy", "laundromat", "warehouse", "factory", "refinery", "power",
  "reservoir", "pipeline", "satellite", "antenna", "billboard", "monument",
  // school & learning
  "lecture", "seminar", "tutorial", "homework", "assignment", "essay",
  "thesis", "dissertation", "scholarship", "tuition", "campus", "dormitory",
  "textbook", "notebook", "pencil", "eraser", "ruler", "calculator", "chalk",
  "diploma", "certificate", "graduation", "semester", "syllabus", "curriculum",
  "geometry", "algebra", "physics", "chemistry", "biology", "astronomy",
  "geography", "literature", "grammar", "vocabulary", "pronunciation",
  // art & media
  "sculpture", "pottery", "embroidery", "knitting", "origami", "collage",
  "exhibit", "portrait", "landscape", "still", "sketch", "doodle", "cartoon",
  "documentary", "sitcom", "drama", "thriller", "comedy", "tragedy", "opera",
  "ballet", "symphony", "orchestra", "melody", "harmony", "lyrics", "chorus",
  "guitar", "violin", "cello", "trumpet", "saxophone", "piano", "drum",
  // science & nature extra
  "gravity", "molecule", "electron", "neutron", "proton", "quantum",
  "ecosystem", "habitat", "species", "organism", "bacteria", "virus",
  "enzyme", "chromosome", "evolution", "fossil", "mineral", "sediment",
  "erosion", "glacier", "avalanche", "volcano", "earthquake", "tornado",
  "hurricane", "cyclone", "monsoon", "horizon", "eclipse", "constellation",
  "galaxy", "nebula", "asteroid", "meteor", "telescope", "microscope",
  // household extra
  "cushion", "pillow", "blanket", "curtain", "carpet", "vacuum", "broom",
  "mop", "sponge", "dishwasher", "microwave", "toaster", "kettle", "blender",
  "cutlery", "napkin", "tray", "vase", "mirror", "frame", "shelf", "drawer",
  "wardrobe", "mattress", "dresser", "nightstand", "rocking", "crib",
  "laundry", "ironing", "sewing", "yarn", "needle", "thread", "scissors",
  // food & drink extra
  "avocado", "broccoli", "spinach", "pumpkin", "zucchini", "eggplant",
  "mushroom", "lentil", "chickpea", "quinoa", "oatmeal", "granola", "yogurt",
  "smoothie", "espresso", "cappuccino", "latte", "smoothie", "lemonade",
  "smoothie", "barbecue", "kebab", "burrito", "taco", "sushi", "ramen",
  "noodle", "dumpling", "pancake", "waffle", "muffin", "croissant", "bagel",
  "cinnamon", "vanilla", "caramel", "coconut", "almond", "walnut", "pistachio",
  // abstract & connectors
  "balance", "pattern", "rhythm", "silence", "echo", "moment", "interval",
  "distance", "direction", "boundary", "border", "edge", "surface", "depth",
  "contrast", "similarity", "difference", "connection", "relationship",
  "sequence", "progress", "process", "structure", "framework", "context",
  "perspective", "approach", "method", "technique", "practice", "routine",
  "habit", "tradition", "culture", "custom", "ritual", "ceremony", "festival",
  "celebration", "memory", "history", "future", "possibility", "chance",
];

// ---------------------------------------------------------------------------
// Verbs.
// ---------------------------------------------------------------------------

// Regular verbs: auto -s / -ing / -ed (standard orthography, no doubling
// unless also listed in DOUBLING_VERBS).
export const REGULAR_VERBS: string[] = [
  "accept", "achieve", "acquire", "address", "admire", "adopt", "afford",
  "agree", "announce", "answer", "apologize", "appear", "applaud", "approve",
  "argue", "arrange", "arrive", "ask", "assist", "attempt", "attend",
  "avoid", "bake", "balance", "ban", "behave", "believe", "belong", "bench", "bless",
  "boil", "borrow", "bother", "breathe", "brush", "calculate", "carry",
  "cause", "celebrate", "challenge", "chant", "charge", "chase", "cheer",
  "chew", "claim", "clean", "clear", "climb", "close", "collect", "combine",
  "complain", "complete", "conclude", "confirm", "connect", "consider",
  "console", "contain", "continue", "cook", "copy", "count", "cover",
  "crash", "create", "cross", "crowd", "crush", "cry", "cure", "curl", "damage",
  "dare", "decide", "decorate", "delay", "deliver", "depend", "describe",
  "deserve", "design", "destroy", "detect", "develop", "devote", "dictate",
  "die", "disagree", "disappear", "discover", "discuss", "dislike", "divide",
  "drag", "dream", "dress", "drift", "dust", "earn", "educate", "embarrass",
  "embrace", "emerge", "emit", "employ", "encourage", "enjoy", "enter",
  "estimate", "examine", "excite", "exercise", "exhibit", "exist", "expect",
  "explain", "explore", "express", "extend", "fail", "fancy", "fasten",
  "feed", "fill", "film", "finish", "fire", "fix", "float", "flood", "flow",
  "fold", "follow", "force", "form", "fry", "gain", "gather", "gaze", "glow",
  "grease", "greet", "grill", "growl", "guess", "handle", "hang", "happen",
  "harm", "hate", "heal", "heat", "help", "hesitate", "hire", "hollow",
  "hope", "hug", "hunt", "hurry", "identify", "ignore", "imagine", "impress",
  "improve", "include", "increase", "influence", "inform", "inherit",
  "inject", "injure", "insist", "inspect", "install", "instruct", "intend",
  "interest", "interfere", "interview", "introduce", "invent", "invite",
  "involve", "irritate", "itch", "jail", "jam", "jest", "join", "joke",
  "judge", "juggle", "jump", "justify", "kick", "kill", "kiss", "kneel",
  "knock", "land", "last", "laugh", "launch", "learn", "lecture", "lick", "lie",
  "lift", "light", "list", "listen", "load", "lock", "long", "look", "lose",
  "love", "maintain", "manage", "mark", "marry", "match", "measure",
  "meditate", "mention", "milk", "mind", "miss", "mix", "monitor", "moor",
  "motivate", "mourn", "move", "multiply", "nail", "need", "negotiate",
  "nod", "note", "notice", "obey", "observe", "obtain", "occur", "offer",
  "open", "operate", "order", "organize", "outline", "overcome", "pack",
  "paint", "park", "part", "pass", "pat", "pause", "perform", "permit",
  "persuade", "pet", "pick", "plant", "play", "please", "point", "polish",
  "pop", "post", "pour", "praise", "pray", "predict", "prefer", "prepare",
  "prescribe", "present", "preserve", "press", "pretend", "prevent",
  "print", "prize", "process", "produce", "promise", "prompt", "propose",
  "protect", "protest", "provide", "publish", "pull", "punch", "punish",
  "purchase", "push", "question", "queue", "quit", "race", "radiate",
  "rain", "raise", "reach", "realize", "receive", "recognize", "recommend",
  "record", "reduce", "refer", "reflect", "refresh", "refuse", "regret",
  "reign", "reject", "relate", "relax", "release", "rely", "remain",
  "remind", "remove", "repair", "repeat", "replace", "reply", "report",
  "request", "rescue", "research", "resemble", "reserve", "resist", "respect",
  "respond", "restore", "retire", "return", "reuse", "review", "reward",
  "rinse", "rip", "rise", "risk", "roar", "roll", "rot", "row", "rub",
  "ruin", "rule", "rush", "sail", "satisfy", "scatter", "scold", "scorch",
  "scratch", "scream", "scrub", "seal", "search", "seat", "select", "sell",
  "serve", "settle", "shade", "share", "shave", "shelter", "shift", "shiver",
  "shock", "shop", "shout", "show", "shrug", "sigh", "sign", "signal",
  "simplify", "sip", "sketch", "ski", "skip", "slam", "slap", "slide",
  "slip", "smash", "smell", "smile", "smoke", "sniff", "snow", "soak",
  "solve", "sort", "sound", "sow", "spark", "spell", "spill", "spin",
  "spot", "spray", "sprout", "squat", "stack", "stain", "stare", "startle",
  "starve", "stay", "steer", "stew", "stir", "stitch", "stop", "store",
  "strap", "strengthen", "stress", "stretch", "strip", "stroke", "stuff",
  "succeed", "suck", "suffer", "suggest", "suit", "supply", "support",
  "suppose", "surf", "surprise", "surround", "survey", "survive", "suspend",
  "swallow", "swear", "sweep", "swell", "swim", "swipe", "switch", "tackle",
  "tag", "tame", "tap", "taste", "tease", "telegraph", "tempt", "tend",
  "tense", "thank", "thaw", "tick", "tickle", "tie", "tighten", "toss",
  "tour", "trace", "track", "trade", "train", "transfer", "transform",
  "translate", "transport", "trap", "travel", "treat", "tremble", "trick",
  "trim", "trip", "trot", "trouble", "trust", "tug", "tutor", "twist",
  "type", "undo", "unite", "unlock", "unpack", "unroll", "update", "urge",
  "use", "vanish", "vary", "vent", "vibrate", "view", "visit", "wail",
  "wander", "warn", "wash", "waste", "watch", "water", "wave", "wedge",
  "welcome", "wet", "whine", "whisper", "whistle", "widen", "wiggle",
  "wipe", "wish", "wobble", "wonder", "worry", "wrap", "wreck", "wriggle",
  "yawn", "yell", "zip", "zoom", "walk", "talk", "work", "call", "care", "live",
  "practice", "study",
];

// Explicit CVC-doubling subset (only these double their final consonant).
export const DOUBLING_VERBS: string[] = [
  "ban", "chat", "chop", "clap", "cram", "dig", "drag", "drop", "fan", "fit",
  "flip", "grab", "grip", "hug", "hum", "jam", "jog",
  "knit", "log", "man", "map", "mob", "mop", "net", "nip", "nod", "pat",
  "pet", "pin", "plan", "plot", "pop", "prop", "quit", "rib", "rip", "rob",
  "rot", "rub", "run", "scan", "scrap", "scrub", "set", "shrug", "slam",
  "slip", "snap", "sob", "spin", "spot", "stop", "stir", "strap", "strip",
  "squat", "swim", "tag", "tap", "trim", "trip", "trot", "wet",
  "whip", "wrap", "zip",
];

// Irregular verbs with explicit forms. Missing keys fall back to regular
// rules; "s" is derived automatically when absent (override for am/be/have).
export const IRREGULAR_VERBS: Record<string, { past?: string; pp?: string; ing?: string; s?: string }> = {
  am: { past: "was", pp: "been", ing: "being", s: "is" },
  be: { past: "was", pp: "been", ing: "being", s: "is" },
  beat: { past: "beat", pp: "beaten", ing: "beating" },
  become: { past: "became", pp: "become", ing: "becoming" },
  begin: { past: "began", pp: "begun", ing: "beginning" },
  bend: { past: "bent", pp: "bent", ing: "bending" },
  bind: { past: "bound", pp: "bound", ing: "binding" },
  bite: { past: "bit", pp: "bitten", ing: "biting" },
  blow: { past: "blew", pp: "blown", ing: "blowing" },
  break: { past: "broke", pp: "broken", ing: "breaking" },
  bring: { past: "brought", pp: "brought", ing: "bringing" },
  build: { past: "built", pp: "built", ing: "building" },
  burn: { past: "burnt", pp: "burnt", ing: "burning" },
  burst: { past: "burst", pp: "burst", ing: "bursting" },
  buy: { past: "bought", pp: "bought", ing: "buying" },
  catch: { past: "caught", pp: "caught", ing: "catching" },
  choose: { past: "chose", pp: "chosen", ing: "choosing" },
  cling: { past: "clung", pp: "clung", ing: "clinging" },
  come: { past: "came", pp: "come", ing: "coming" },
  creep: { past: "crept", pp: "crept", ing: "creeping" },
  cut: { past: "cut", pp: "cut", ing: "cutting" },
  deal: { past: "dealt", pp: "dealt", ing: "dealing" },
  dig: { past: "dug", pp: "dug", ing: "digging" },
  dive: { past: "dove", pp: "dived", ing: "diving" },
  do: { past: "did", pp: "done", ing: "doing" },
  draw: { past: "drew", pp: "drawn", ing: "drawing" },
  drink: { past: "drank", pp: "drunk", ing: "drinking" },
  drive: { past: "drove", pp: "driven", ing: "driving" },
  eat: { past: "ate", pp: "eaten", ing: "eating" },
  fall: { past: "fell", pp: "fallen", ing: "falling" },
  feed: { past: "fed", pp: "fed", ing: "feeding" },
  feel: { past: "felt", pp: "felt", ing: "feeling" },
  fight: { past: "fought", pp: "fought", ing: "fighting" },
  find: { past: "found", pp: "found", ing: "finding" },
  flee: { past: "fled", pp: "fled", ing: "fleeing" },
  fling: { past: "flung", pp: "flung", ing: "flinging" },
  fly: { past: "flew", pp: "flown", ing: "flying" },
  forget: { past: "forgot", pp: "forgotten", ing: "forgetting" },
  forgive: { past: "forgave", pp: "forgiven", ing: "forgiving" },
  freeze: { past: "froze", pp: "frozen", ing: "freezing" },
  get: { past: "got", pp: "gotten", ing: "getting" },
  give: { past: "gave", pp: "given", ing: "giving" },
  go: { past: "went", pp: "gone", ing: "going" },
  grow: { past: "grew", pp: "grown", ing: "growing" },
  hang: { past: "hung", pp: "hung", ing: "hanging" },
  have: { past: "had", pp: "had", ing: "having", s: "has" },
  hear: { past: "heard", pp: "heard", ing: "hearing" },
  hide: { past: "hid", pp: "hidden", ing: "hiding" },
  hit: { past: "hit", pp: "hit", ing: "hitting" },
  hold: { past: "held", pp: "held", ing: "holding" },
  hurt: { past: "hurt", pp: "hurt", ing: "hurting" },
  keep: { past: "kept", pp: "kept", ing: "keeping" },
  kneel: { past: "knelt", pp: "knelt", ing: "kneeling" },
  know: { past: "knew", pp: "known", ing: "knowing" },
  lay: { past: "laid", pp: "laid", ing: "laying" },
  lead: { past: "led", pp: "led", ing: "leading" },
  lean: { past: "leant", pp: "leant", ing: "leaning" },
  leap: { past: "leapt", pp: "leapt", ing: "leaping" },
  leave: { past: "left", pp: "left", ing: "leaving" },
  lend: { past: "lent", pp: "lent", ing: "lending" },
  let: { past: "let", pp: "let", ing: "letting" },
  lie: { past: "lay", pp: "lain", ing: "lying" },
  light: { past: "lit", pp: "lit", ing: "lighting" },
  lose: { past: "lost", pp: "lost", ing: "losing" },
  make: { past: "made", pp: "made", ing: "making" },
  mean: { past: "meant", pp: "meant", ing: "meaning" },
  meet: { past: "met", pp: "met", ing: "meeting" },
  pay: { past: "paid", pp: "paid", ing: "paying" },
  put: { past: "put", pp: "put", ing: "putting" },
  quit: { past: "quit", pp: "quit", ing: "quitting" },
  read: { past: "read", pp: "read", ing: "reading" },
  ride: { past: "rode", pp: "ridden", ing: "riding" },
  ring: { past: "rang", pp: "rung", ing: "ringing" },
  rise: { past: "rose", pp: "risen", ing: "rising" },
  run: { past: "ran", pp: "run", ing: "running" },
  say: { past: "said", pp: "said", ing: "saying" },
  seek: { past: "sought", pp: "sought", ing: "seeking" },
  sell: { past: "sold", pp: "sold", ing: "selling" },
  send: { past: "sent", pp: "sent", ing: "sending" },
  set: { past: "set", pp: "set", ing: "setting" },
  shake: { past: "shook", pp: "shaken", ing: "shaking" },
  shine: { past: "shone", pp: "shone", ing: "shining" },
  shoot: { past: "shot", pp: "shot", ing: "shooting" },
  show: { past: "showed", pp: "shown", ing: "showing" },
  shut: { past: "shut", pp: "shut", ing: "shutting" },
  sing: { past: "sang", pp: "sung", ing: "singing" },
  sink: { past: "sank", pp: "sunk", ing: "sinking" },
  sit: { past: "sat", pp: "sat", ing: "sitting" },
  sleep: { past: "slept", pp: "slept", ing: "sleeping" },
  slide: { past: "slid", pp: "slid", ing: "sliding" },
  sneak: { past: "snuck", pp: "snuck", ing: "sneaking" },
  speak: { past: "spoke", pp: "spoken", ing: "speaking" },
  spend: { past: "spent", pp: "spent", ing: "spending" },
  spill: { past: "spilt", pp: "spilt", ing: "spilling" },
  spin: { past: "spun", pp: "spun", ing: "spinning" },
  spit: { past: "spat", pp: "spat", ing: "spitting" },
  split: { past: "split", pp: "split", ing: "splitting" },
  spread: { past: "spread", pp: "spread", ing: "spreading" },
  stand: { past: "stood", pp: "stood", ing: "standing" },
  steal: { past: "stole", pp: "stolen", ing: "stealing" },
  stick: { past: "stuck", pp: "stuck", ing: "sticking" },
  sting: { past: "stung", pp: "stung", ing: "stinging" },
  strike: { past: "struck", pp: "struck", ing: "striking" },
  strive: { past: "strove", pp: "striven", ing: "striving" },
  swear: { past: "swore", pp: "sworn", ing: "swearing" },
  sweep: { past: "swept", pp: "swept", ing: "sweeping" },
  swell: { past: "swelled", pp: "swollen", ing: "swelling" },
  swim: { past: "swam", pp: "swum", ing: "swimming" },
  swing: { past: "swung", pp: "swung", ing: "swinging" },
  take: { past: "took", pp: "taken", ing: "taking" },
  teach: { past: "taught", pp: "taught", ing: "teaching" },
  tear: { past: "tore", pp: "torn", ing: "tearing" },
  tell: { past: "told", pp: "told", ing: "telling" },
  think: { past: "thought", pp: "thought", ing: "thinking" },
  throw: { past: "threw", pp: "thrown", ing: "throwing" },
  understand: { past: "understood", pp: "understood", ing: "understanding" },
  undo: { past: "undid", pp: "undone", ing: "undoing" },
  wake: { past: "woke", pp: "woken", ing: "waking" },
  wear: { past: "wore", pp: "worn", ing: "wearing" },
  weave: { past: "wove", pp: "woven", ing: "weaving" },
  weep: { past: "wept", pp: "wept", ing: "weeping" },
  win: { past: "won", pp: "won", ing: "winning" },
  wind: { past: "wound", pp: "wound", ing: "winding" },
  withdraw: { past: "withdrew", pp: "withdrawn", ing: "withdrawing" },
  wring: { past: "wrung", pp: "wrung", ing: "wringing" },
  write: { past: "wrote", pp: "written", ing: "writing" },
};

// ---------------------------------------------------------------------------
// Nouns — auto plurals (regular -s/-es/-ies only). Irregular plural spellings
// live in PLURAL_MAP. Bases are ensured to exist in the pool.
// ---------------------------------------------------------------------------
export const PLURAL_NOUNS: string[] = [
  "animal", "ankle", "answer", "apple", "arrow", "artist", "author", "autumn",
  "bag", "baker", "balcony", "ball", "balloon", "banana", "bar", "barrel",
  "basket", "bath", "battery", "beach", "beam", "bean", "bear", "beard",
  "beat", "bed", "bee", "bell", "belt", "bench", "berry", "bicycle", "bill",
  "bird", "birthday", "biscuit", "bishop", "blade", "blanket", "block",
  "blouse", "board", "boat", "body", "boiler", "bone", "book", "boot",
  "border", "bottle", "bowl", "box", "brain", "brake", "branch", "brass",
  "bread", "brick", "bridge", "broom", "brush", "bucket", "building", "bulb",
  "bull", "bun", "bush", "business", "butcher", "butter", "button", "cabbage",
  "cable", "cake", "calculator", "calendar", "camera", "camp", "candle",
  "cap", "car", "card", "care", "carpet", "carrot", "cart", "case", "cash",
  "castle", "cat", "ceiling", "cell", "cent", "chain", "chair",
  "chalk", "chance", "change", "channel", "chapter", "charity", "chart",
  "cheek", "cheese", "chef", "chemist", "cherry", "chimney", "chin", "chip",
  "chocolate", "church", "cinema", "circle", "city", "clam", "clerk", "cliff",
  "clock", "cloth", "cloud", "club", "coach", "coast", "coat", "code",
  "coffee", "coin", "collar", "colleague", "college", "column", "comb",
  "comedy", "computer", "concert", "cone", "corner", "corridor", "cottage",
  "cotton", "cough", "country", "course", "court", "cousin", "cow", "crab",
  "crash", "crayon", "cream", "crib", "cricket", "crime", "crowd", "crown",
  "crumb", "crystal", "cup", "cupboard", "curtain", "curve", "cushion",
  "customer", "cyclone", "dancer", "deck", "degree", "dentist",
  "desk", "dessert", "diploma", "dish", "doctor", "doll", "dollar", "dolphin",
  "donkey", "door", "dot", "doughnut", "dragon", "drawer", "dream", "dress",
  "drill", "drink", "driver", "drum", "duck", "dustbin", "eagle", "ear",
  "earthquake", "edge", "egg", "elbow", "elephant", "email", "engine",
  "entrance", "envelope", "error", "essay", "estate", "evening", "event",
  "exam", "exit", "eye", "face", "factory", "fairy", "falcon", "farm",
  "farmer", "fashion", "fence", "fern", "ferry", "field", "fig", "finger",
  "fire", "fireman", "fish", "fist", "flag", "flame", "flavor", "flea",
  "flesh", "flight", "floor", "flower", "flute", "foam", "fog", "fold",
  "folder", "food", "foot", "football", "forest", "fork", "form", "fountain",
  "fox", "frame", "frog", "front", "frost", "fruit", "funeral", "fur",
  "gale", "gallon", "game", "garage", "garden", "garlic",
  "gate", "gear", "gem", "gentleman", "ghost", "giant", "giraffe", "girl",
  "glass", "glove", "glue", "goat", "golf", "gong", "gorilla",
  "grain", "granite", "grape", "grass", "grave", "gray", "green", "grid",
  "grocer", "ground", "group", "guard", "guitar", "gun", "gym", "hall",
  "ham", "hammer", "hand", "harbor", "harmony", "harvest", "hat", "hatch",
  "hawk", "hay", "head", "heart", "heat", "hedge", "heel", "helmet", "hen",
  "herd", "hero", "herring", "hill", "hinge", "hobby", "hole",
  "holiday", "home", "honey", "hood", "hoof", "hook", "horn", "horse",
  "hose", "hospital", "host", "hotel", "hound", "house", "hut", "ice",
  "idea", "ink", "insect", "instrument", "iron", "island", "jacket", "jade",
  "jar", "jaw", "jeep", "jet", "jewel", "job", "jug", "juice",
  "jungle", "kayak", "kettle", "key", "keyboard", "kid", "kidney", "king",
  "kitchen", "kite", "knee", "knife", "knight", "knot", "lab", "ladder",
  "ladle", "lamb", "lamp", "lantern", "lap", "larch", "leaf", "league",
  "learner", "leather", "lecture", "leg", "lemon", "lens", "lentil", "leopard",
  "letter", "lettuce", "level", "library", "lift", "light", "lily", "limb",
  "lime", "line", "linen", "lion", "lip", "liquid", "list", "liter", "litter",
  "lizard", "lobby", "lobster", "lock", "loaf", "lobby", "locket", "locomotive",
  "log", "lorry", "loss", "lot", "lung", "machine", "magazine",
  "magnet", "maid", "mail", "manager", "map", "marble", "margin", "market",
  "marrow", "mask", "mattress", "melon", "member", "memory", "menu", "mercury",
  "mess", "message", "metal", "meter", "method", "microscope", "midnight",
  "milk", "mill", "million", "mind", "mineral", "mint", "minute", "mirror",
  "mist", "mistake", "mitten", "model", "moment", "monastery",
  "monkey", "monsoon", "month", "moon", "morning", "mosquito", "moss", "mother",
  "motor", "mountain", "mouse", "mouth", "movie", "mud", "muffin", "mug",
  "muscle", "museum", "nail", "napkin", "nation", "nature", "neck",
  "necklace", "needle", "nest", "net", "network", "newspaper", "night",
  "noodle", "noon", "nose", "note", "notebook", "novel", "number",
  "nurse", "nut", "oak", "oar", "oat", "ocean", "office", "oil", "olive",
  "onion", "orange", "orchard", "organ", "ostrich", "otter", "ounce", "oven",
  "owl", "owner", "ox", "oyster", "packet", "paddle", "page", "paint",
  "painter", "palace", "palm", "pan", "pancake", "panda", "panel", "panther",
  "pant", "paper", "parade", "parcel", "parent", "park", "parrot", "part",
  "party", "passenger", "passport", "pastry", "patch", "path",
  "patient", "patio", "pavement", "paw", "payment", "peach", "peak",
  "peanut", "pear", "pearl", "pebble", "pedal", "pelican", "pencil",
  "pendulum", "penguin", "pen", "pepper", "perch", "period", "permit",
  "person", "pet", "petal", "pew", "pharmacy", "phase", "phone", "photo",
  "phrase", "piano", "picnic", "picture", "pie", "piece", "pier",
  "pig", "pigeon", "pillow", "pilot", "pin", "pine", "pipe", "pistol",
  "pitch", "pizza", "place", "plague", "plan", "plane", "planet", "plank",
  "plant", "plaster", "plastic", "plate", "player", "plaza", "pledge",
  "plot", "plough", "plow", "plug", "plum", "pocket", "pod", "poem", "poet",
  "point", "poison", "police", "policeman", "policy", "pond", "pony", "pool",
  "port", "portrait", "post", "postage", "postcard", "pot", "potato",
  "pouch", "pound", "powder", "power", "prawn", "prayer",
  "present", "president", "press", "pressure", "price", "priest", "prince",
  "princess", "print", "prism", "prison", "prize", "profit", "program",
  "project", "promise", "prompt", "proof", "property", "prospect", "protein",
  "puppy", "pulse", "pump", "pupil", "purchase", "purse", "puzzle", "pyramid",
  "quality", "quantity", "quart", "queen", "question", "quilt",
  "rabbit", "race", "rack", "radar", "radiator", "radio", "radish", "rafter",
  "rag", "rail", "railway", "rain", "rainbow", "rake", "ranch", "range",
  "rat", "rate", "ray", "razor", "reaction", "record", "rectangle", "reed",
  "reef", "refrigerator", "region", "relation", "religion", "reptile",
  "resort", "restaurant", "result", "rhythm", "ribbon", "rice", "riddle",
  "rider", "ridge", "rifle", "ring", "ripen", "river", "road", "roast",
  "robin", "robot", "rock", "rocket", "rod", "roller", "roof", "room",
  "rooster", "root", "rope", "rose", "rotor", "row", "rubber", "rug", "ruin",
  "rule", "ruler", "rumor", "runner", "rush", "sack", "saddle", "sailor",
  "salad", "salt", "sand", "sandwich", "sardine", "satellite",
  "sauce", "saucer", "sausage", "savage", "saw", "scarecrow", "scarf",
  "scene", "scent", "scheme", "school", "science", "scooter",
  "scorer", "screen", "screw", "script", "sculpture", "sea", "seal", "season",
  "seat", "second", "secretary", "seed", "sensor", "sentence", "servant",
  "shadow", "shampoo", "shape", "shark", "shawl", "sheet", "shelf",
  "shell", "shelter", "shield", "ship", "shirt", "shock", "shoe", "shop",
  "shore", "shot", "shoulder", "shrimp", "shrub", "shutter",
  "side", "sign", "signal", "signature", "silk", "silence", "singer",
  "sink", "sister", "skate", "sketch", "ski", "skirt", "sky", "sled",
  "sleeve", "slipper", "slope", "smash", "smell", "smile", "smoke", "snail",
  "snake", "sneeze", "snow", "soap", "sock", "sofa",
  "soldier", "son", "song", "sort", "sound", "soup", "source",
  "space", "spade", "spaghetti", "speaker", "spear", "speech", "sphere",
  "spice", "spider", "spike", "spine", "spinach", "spiral", "spirit", "sponge",
  "spoon", "sport", "spot", "spray", "spring", "sprout", "spruce", "square",
  "squash", "squid", "squirrel", "stage", "stair", "stall", "stamp", "stand",
  "star", "starling", "starter", "statue", "steam", "steel", "stem", "step",
  "stick", "stitch", "stock", "stomach", "stone", "stool", "stop", "storage",
  "stork", "story", "stove", "stranger", "strap", "straw", "stream", "street",
  "stripe", "stroke", "structure", "student", "studio", "stuff",
  "sty", "sugar", "suit", "summer", "sun", "sunlight", "sunrise", "sunset",
  "supermarket", "supper", "surf", "surgeon", "surprise", "swallow", "swamp",
  "swan", "sweater", "swimmer", "sword", "symphony", "syrup", "table",
  "tablet", "tackle", "tail", "tailor", "tale", "talk", "tank", "tap",
  "tape", "target", "task", "taste", "taxi", "tea", "teacher", "team",
  "tear", "technique", "television", "temper", "temple", "tenant",
  "tendency", "tennis", "tent", "territory", "text", "textbook", "theater",
  "theme", "theory", "thief", "thermometer", "thistle", "thorn", "thread",
  "throat", "throne", "thumb", "thunder", "ticket", "tide", "tiger",
  "timber", "timetable", "tin", "tissue", "title", "toast", "toe", "tomato",
  "ton", "tongue", "tooth", "toothpaste", "top", "torch", "tornado", "tortoise",
  "tower", "town", "toy", "track", "tractor", "trade", "traffic", "trail",
  "train", "tram", "tramp", "transfer", "traveler", "tray", "treasure",
  "treat", "tree", "tremble", "trench", "triangle", "tribe", "trick",
  "trinket", "trolley", "troop", "trophy", "truck",
  "trumpet", "trunk", "trust", "truth", "tulip", "tummy", "tunnel", "turkey",
  "turnip", "turtle", "tusk", "tutor", "twilight", "twist", "typhoon",
  "umbrella", "uncle", "uniform", "unit", "university", "vacuum", "valley",
  "value", "valve", "van", "vase", "vault", "vegetable", "vehicle", "veil",
  "vein", "velvet", "vendor", "veranda", "verse", "version", "vessel",
  "veteran", "village", "vine", "violin", "virus", "visa", "vision", "visitor",
  "vitamin", "voice", "volcano", "volleyball", "voyage", "wafer", "wagon",
  "waist", "waiter", "wardrobe", "war", "warning", "warrior",
  "washbasin", "wasp", "waste", "watch", "water", "waterfall", "wave", "wax",
  "way", "weakness", "weapon", "weather", "weaver", "web", "wedge",
  "week", "weight", "welcome", "well", "whale", "wheat", "wheel",
  "whisker", "whiskey", "whisper", "whistle", "wick", "widow", "width",
  "wife", "wig", "wilderness", "willow", "wind", "windmill", "window",
  "wing", "winter", "wire", "wisdom", "wizard", "wolf", "wonder",
  "wood", "wool", "word", "workshop", "world", "worm", "wound", "wrap",
  "wreath", "wren", "wrench", "wrist", "writer", "yard", "yarn", "year",
  "yawn", "yell", "yew", "yogurt", "yolk", "zebra", "zephyr", "zinc", "zip",
  "zipper", "zodiac", "zone", "zoo",
];

// Explicit irregular/special plurals (base -> plural). Base emitted too.
export const PLURAL_MAP: Record<string, string> = {
  leaf: "leaves", loaf: "loaves", thief: "thieves", wolf: "wolves",
  calf: "calves", half: "halves", shelf: "shelves", knife: "knives",
  wife: "wives", life: "lives", scarf: "scarves", hoof: "hooves",
  man: "men", woman: "women", child: "children", foot: "feet",
  tooth: "teeth", goose: "geese", mouse: "mice", louse: "lice",
  person: "people", ox: "oxen", potato: "potatoes", tomato: "tomatoes",
  hero: "heroes", echo: "echoes", veto: "vetoes", torpedo: "torpedoes",
  embargo: "embargoes",
};

// ---------------------------------------------------------------------------
// Adjectives — comparatives/superlatives (short gradable words only;
// longer adjectives take more/most and are NOT inflected).
// ---------------------------------------------------------------------------
export const GRADABLE_ADJECTIVES: string[] = [
  "angry", "big", "bitter", "brave", "bright", "broad", "busy", "calm",
  "cheap", "clean", "clear", "cold", "cool", "cozy", "crazy", "cruel",
  "curly", "dark", "deep", "dense", "dirty", "dry", "dull", "early", "easy",
  "faint", "fancy", "fast", "fat", "fine", "firm", "flat", "fond", "fresh",
  "friendly", "funny", "fuzzy", "glad", "grand", "great", "green", "grim",
  "happy", "hard", "harsh", "hasty", "heavy", "high", "hungry", "kind",
  "large", "late", "light", "lonely", "long", "loud", "lovely", "low",
  "lucky", "mad", "mellow", "mild", "neat", "new", "nice", "noisy", "odd",
  "plain", "pretty", "proud", "pure", "quick", "quiet", "rare", "rich",
  "rough", "round", "sad", "safe", "salty", "short", "shy", "silly", "slim",
  "slow", "small", "smart", "smooth", "soft", "stale", "steady", "stiff",
  "strange", "strict", "strong", "sturdy", "sunny", "sweet",
  "swift", "tall", "tame", "tasty", "thick", "thin", "tidy", "tight",
  "tiny", "tough", "tricky", "vast", "warm", "weak", "wealthy", "weird",
  "wet", "wide", "wild", "wise", "young", "zesty",
];

// CVC-doubling subset for comparatives (big->bigger etc.).
export const DOUBLING_ADJECTIVES: string[] = ["big", "sad", "mad", "thin", "slim", "glad"];

// ---------------------------------------------------------------------------
// Adverbs — curated adjectives that form clean -ly adverbs.
// ---------------------------------------------------------------------------
export const ADVERB_BASES: string[] = [
  "actual", "angry", "apparent", "bad", "basic", "beautiful", "bitter",
  "brave", "brief", "bright", "brilliant", "busy", "calm", "careful",
  "casual", "cautious", "certain", "cheerful", "chilly", "clever", "cold",
  "complete", "confident", "constant", "correct", "crazy", "curious",
  "current", "dark", "deep", "definite", "different", "distant",
  "dramatic", "eager", "early", "eager", "easy", "elegant", "excellent",
  "excited", "exact", "extreme", "fair", "faithful", "famous", "fancy",
  "final", "fine", "firm", "flexible", "fond", "foolish", "formal",
  "fortunate", "frequent", "friendly", "gentle", "genuine", "glad", "general",
  "global", "graceful", "grateful", "great", "guilty", "happy", "harsh",
  "hasty", "healthy", "heavy", "honest", "hopeful", "huge", "humble",
  "hungry", "immediate", "important", "impossible", "informal",
  "instant", "intense", "internal", "keen", "kind", "large", "late", "lucky",
  "loud", "mad", "magic", "manual", "mental", "mild", "modern", "modest",
  "natural", "near", "neat", "nervous", "new", "nice", "noisy", "normal",
  "obvious", "odd", "original", "patient", "peaceful", "perfect",
  "personal", "playful", "pleasant", "polite", "poor", "proud", "proper",
  "pure", "quick", "quiet", "rare", "real", "recent", "regular", "relative",
  "reluctant", "remarkable", "remote", "respectful", "responsible", "rich",
  "rough", "round", "rude", "sad", "safe", "sensitive", "serious",
  "severe", "sharp", "shy", "sick", "significant", "silent", "similar",
  "simple", "sincere", "slow", "smooth", "soft", "solemn", "solid",
  "sorrowful", "special", "steady", "strange", "strict", "strong",
  "stupid", "subtle", "successful", "sudden", "sufficient", "sure", "sweet",
  "swift", "tender", "terrible", "thorough", "tidy", "tight", "tiny",
  "total", "tough", "tragic", "true", "typical", "urgent", "usual", "vague",
  "various", "vast", "virtual", "vital", "vivid", "warm", "weak", "weird",
  "wide", "wild", "willing", "wise", "wonderful", "young",
];

// ---------------------------------------------------------------------------
// Explicit derivations (base -> derived word). Only common, unambiguous ones.
// ---------------------------------------------------------------------------
export const DERIVED: Record<string, string> = {
 // -ness
 happy: "happiness", sad: "sadness", kind: "kindness", dark: "darkness",
 weak: "weakness", ill: "illness", tired: "tiredness", lazy: "laziness",
 great: "greatness", bitter: "bitterness", cold: "coldness", cool: "coolness",
 dull: "dullness", faint: "faintness", firm: "firmness", gentle: "gentleness",
 good: "goodness", harsh: "harshness", honest: "honesty", mad: "madness",
 nice: "niceness", polite: "politeness", proud: "pride", quick: "quickness",
 quiet: "quietness", raw: "rawness", rich: "richness", rough: "roughness",
 sharp: "sharpness", shy: "shyness", sick: "sickness", silly: "silliness",
 smooth: "smoothness", soft: "softness", steady: "steadiness", stiff: "stiffness",
 strange: "strangeness", sweet: "sweetness", tall: "tallness", thick: "thickness",
 thin: "thinness", tough: "toughness", warm: "warmth", wealthy: "wealth",
 weird: "weirdness", wide: "width", wild: "wildness", willing: "willingness",
 friendly: "friendliness", lonely: "loneliness", lovely: "loveliness",
 forgetful: "forgetfulness", graceful: "gracefulness", helpful: "helpfulness",
 // -ment
 agree: "agreement", adjust: "adjustment", arrange: "arrangement",
 amuse: "amusement", announce: "announcement", argue: "argument",
 assign: "assignment", attach: "attachment", achieve: "achievement",
 advertise: "advertisement", encourage: "encouragement", equip: "equipment",
 improve: "improvement", invest: "investment", involve: "involvement",
 manage: "management", measure: "measurement", pay: "payment",
 place: "placement", punish: "punishment", refresh: "refreshment",
 replace: "replacement", require: "requirement", retire: "retirement",
 state: "statement", treat: "treatment", develop: "development",
 govern: "government", employ: "employment", enjoy: "enjoyment",
 engage: "engagement", judge: "judgment", acknowledge: "acknowledgment",
 commit: "commitment", appoint: "appointment", amaze: "amazement",
 // -tion / -sion / -ition
 educate: "education", create: "creation", relate: "relation",
 connect: "connection", protect: "protection", direct: "direction",
 invent: "invention", suggest: "suggestion", celebrate: "celebration",
 collect: "collection", combine: "combination", examine: "examination",
 imagine: "imagination", invite: "invitation", prepare: "preparation",
 produce: "production", reduce: "reduction", repeat: "repetition",
 solve: "solution", attract: "attraction", distract: "distraction",
 instruct: "instruction", construct: "construction", describe: "description",
 subscribe: "subscription", prescribe: "prescription", decide: "decision",
 divide: "division", provide: "provision", confuse: "confusion",
 express: "expression", impress: "impression", possess: "possession",
 discuss: "discussion", permit: "permission", admit: "admission",
 transmit: "transmission", submit: "submission", omit: "omission",
 apply: "application", imply: "implication", simplify: "simplification",
 verify: "verification", justify: "justification", identify: "identification",
 qualify: "qualification", notify: "notification", modify: "modification",
 specify: "specification", satisfy: "satisfaction", purify: "purification",
 communicate: "communication", cooperate: "cooperation", operate: "operation",
 compete: "competition", complete: "completion", explain: "explanation",
 observe: "observation", preserve: "preservation", reserve: "reservation",
 starve: "starvation", migrate: "migration", motivate: "motivation",
 organize: "organization", realize: "realization", recognize: "recognition",
 inform: "information", introduce: "introduction",
 decorate: "decoration", demonstrate: "demonstration", concentrate: "concentration",
 // agent nouns (-er / -or)
 build: "builder", read: "reader", drive: "driver", swim: "swimmer",
 climb: "climber", own: "owner", buy: "buyer", sell: "seller",
 travel: "traveler", sing: "singer", dance: "dancer", paint: "painter",
 report: "reporter", design: "designer",
 inspect: "inspector", sail: "sailor", edit: "editor",
 visit: "visitor",
 translate: "translator", survive: "survivor",
 run: "runner", win: "winner", plan: "planner",
 jog: "jogger", dig: "digger", cut: "cutter", knit: "knitter",
 spin: "spinner", hunt: "hunter", farm: "farmer", bake: "baker",
 make: "maker", give: "giver", love: "lover", move: "mover", use: "user",
 ride: "rider", smoke: "smoker", joke: "joker", speak: "speaker",
 listen: "listener", learn: "learner", clean: "cleaner", cook: "cooker",
 walk: "walker", print: "printer", wait: "waiter", serve: "server",
 code: "coder", program: "programmer", scan: "scanner", track: "tracker",
 hack: "hacker", blog: "blogger", stream: "streamer", game: "gamer",
 trade: "trader", keep: "keeper", find: "finder", bind: "binder",
 grind: "grinder", write: "writer", teach: "teacher", work: "worker",
 play: "player", lead: "leader", act: "actor",
 conduct: "conductor", project: "projector",
 // -ian / other
 history: "historian", library: "librarian", music: "musician",
 politics: "politician", electric: "electrician", magic: "magician",
 comedy: "comedian", statistics: "statistician", diet: "dietitian",
 hero: "heroine", philosophy: "philosopher", economy: "economist",
 psychology: "psychologist", science: "scientist", art: "artist",
 type: "typist", tour: "tourist", cycle: "cyclist", special: "specialist",
 journal: "journalist", novel: "novelist",
};
